pipeline {
    agent any
    stages {
        stage("Clone Git Repository") {
            steps {
                git(
                    git branch: 'Testing', credentialsId: 'git', url: 'https://github.com/rohanmane21/Python.git',
                    branch: "Testing",
                    changelog: true,
                    poll: true
                )
            }
        }
    }
}
